#include "DaConstants.h"

UE_DEFINE_GAMEPLAY_TAG(TAG_PICKUP, "Pickup")
UE_DEFINE_GAMEPLAY_TAG(TAG_PICKUP_HEALTH, "Pickup.Health")
UE_DEFINE_GAMEPLAY_TAG(TAG_PICKUP_CREDITS, "Pickup.Credits")

UE_DEFINE_GAMEPLAY_TAG(TAG_ACTION_BUFF, "Action.Buff");
UE_DEFINE_GAMEPLAY_TAG(TAG_ACTION_BUFF_THORNS, "Action.Buff.Thorns");

