#pragma once

#include "NativeGameplayTags.h"

namespace SharedGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_PICKUP);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_PICKUP_HEALTH);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_PICKUP_CREDITS);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ACTION_BUFF);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ACTION_BUFF_THORNS);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Sprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_PrimaryAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_SecondaryAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Blackhole);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Dash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Parry);
}
